workflows:
  android-apk:
    name: Android APK
    environment:
      node: 18
      java: 17
      android_signing:
        - flashcards_keystore
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Set Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android release APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleRelease --no-daemon -x bundleReleaseJsAndAssets
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
